- name: Create buildbox group
  group: name={{ buildbox_group }} system=yes

- name: Create buildbox user
  user: name={{ buildbox_user }} comment="buildbox" group={{ buildbox_group }} home={{ buildbox_home }} system=yes

- name: Create .buildbox directory
  file: path={{ buildbox_home }}/.buildbox owner={{ buildbox_user }} group={{ buildbox_group }} mode=0755 state=directory

- name: Create .buildbox/bin directory
  file: path={{ buildbox_home }}/.buildbox/bin owner={{ buildbox_user }} group={{ buildbox_group }} mode=0755 state=directory

- name: Download buildbox agent
  get_url: url=https://github.com/buildbox/agent/releases/download/v{{ buildbox_version }}/buildbox-agent-linux-{{ buildbox_arch }}.tar.gz dest=/tmp/buildbox-agent-linux-{{ buildbox_arch }}.tar.gz

- name: Extract buildbox agent
  command: tar -xvzf /tmp/buildbox-agent-linux-{{ buildbox_arch }}.tar.gz -C {{ buildbox_home }}/.buildbox/bin

- name: Configure boostrap file
  template: src=bootstrap.j2 dest={{ buildbox_home }}/.buildbox/bootstrap.sh owner={{ buildbox_user }} group={{ buildbox_group }} mode=0774

- name: Configure upstart
  template: src=upstart.j2 dest=/etc/init/buildbox-agent.conf
